### ISSUE TITLE
Add the function of calculating Bridge closeness and bridge betweenness with both positive and negative edges.

### ISSUE THREAD

**Issue by Shunsenhuang-123** [paytonjjones/networktools#4]
Dear Payton Jones, 
Thank your development and updates on the package "networktools", and I have an idea for your package "networktools".

In the reference manual, you write that "If negative edges exist, bridge expected influence should be used. Bridge closeness and bridge betweenness are only defined for positive edge weights, thus negative edges, if present, are deleted in the calculation of these metrics."

My idea is that add the function of calculating Bridge closeness and bridge betweenness with both positive and negative edges. This is because, although the closeness or betweenness might be unstable according to the sample size, there urges practical demands for this function. The reasons are as follows:
First, when the sample size is large enough, the two indicators can be stable.
Second, the two indicators have their unique aspects beyond the strength or bridge strength. Image that the network system include not just emotional disorders (e.g., depression or anxiety symptoms), but also nodes involving behaviors, cognition, and environment (e.g., family or school environments), the betweenness and closeness show their uniqueness. For example, emotional disorders, behaviors, cognition, family environment, and school environment represent different systems, and the path flow between them have practical meaning. A emotional symptoms would not be affected by family environment, but it can be mediated by the cognition or behavior systems, which highlights the role of the two indicators. 
Besides, some researchers (e.g., Bringmann, 2019) argued that if just rely on strength, there might be no essential difference with regressions (if regression can determine the important one, why we need network analysis again?).
Thus, I think add the function to your package would promote its' use and spread, because there are practical needs for this.

Or if you already have a similar idea, can you tell us, for example, how can we revise the existing function to include the negative edge in calculating the two indicators.  I am not a statistician in network analysis, I just put this idea from a practical perspective, and it can supplement the existing functions of the package, I think.

Best wishes, 
Shunsen

**Comment by paytonjjones** [comment]
Hi Shunsen,

Sorry for the delay in my reply.

Unfortunately, the issue of negative weights in graph theory and centrality metrics is broader than bridge centrality, and not truly solvable. If you look around, you'll find the same (or similar) limitations in other software that computes closeness or betweenness metrics. 

Specifically, closeness and betweenness rely on algorithms for computing the shortest path between nodes. In some cases, this is technically possible even with negative edges, though the meaning of "shortest path" becomes a little tenuous. However, if there are any negative _cycles_ in the graph, finding a shortest path becomes impossible (as a negative cycle is infinitely "short").

If the negative edges in your network are extremely small to the point of being meaningless, it might be justifiable to simply ignore these edges in the calculation of bridge betweenness or bridge closeness. As you've noted, this is the current package default. Another approach in such a scenario would be using thresholding or shrinkage to remove _all_ trivially small edges (positive and negative). 

In psychological network analyses, there may also be cases where it is justifiable to "reverse" a vertex, such as reversing extraversion to introversion, which may help remove negative edges from the network. 

I hope this clarifies the issue!
-Payton
